cd "%~dp0"
call build-msinttypes.bat "/wait" "--hold error"
call build-yasm.bat "/wait" "--hold error"
call build-bzip2.bat "/wait" "--hold error"
call build-libav.bat "/wait" "--hold error"
call build-l-smash.bat "/wait" "--hold error"
call build-L-SMASH-Works-libav-AviUtl.bat "/wait" "--hold error"
call build-L-SMASH-Works-libav-VapourSynth.bat "/wait" "--hold error"
call build-L-SMASH-Works-libav-AviSynth.bat "/wait" "--hold error"
call build-ffmpeg.bat "/wait" "--hold error"
call build-L-SMASH-Works-ffmpeg-AviUtl.bat "/wait" "--hold error"
call build-L-SMASH-Works-ffmpeg-VapourSynth.bat "/wait" "--hold error"
call build-L-SMASH-Works-ffmpeg-AviSynth.bat "/wait" "--hold error"
pause
